public enum ObjectType
{
    ConstructPlace,
    ConstructRotatedPlace,
    SmallRoom,
    MediumRoom,
    RotatedMediumRoom,
    BigRoom,
    Road,
    RoadRotated,
    CrossRoad,
    LRoad,
    LRoadRotated90,
    LRoadRotated180,
    LRoadRotated270,
    TRoad,
    TRoadRotated90,
    TRoadRotated180,
    TRoadRotated270,
    Crew,
    Pointer,
    MergeButton
}